### ISSUE TITLE
Image link path [Q]

### ISSUE THREAD

**Issue by contrapunctus-1** [gsantner/markor#577]
I have a folder on my microSD card, containing a file.md and some images. I created the file in Emacs, and added links in it for the images. These showed up inline in Emacs, but not on Markor. I tried adding a link in Markor, and it said that "the file is not in the same folder", and asked me if I'd like to copy it to this folder. Creating the link without that results in a broken link... :thinking:

Investigating a little further, I found that the malfunctioning links had spaces in the file names, which my links didn't replace with %20 (doing this by hand fixed it). I'd need to check what the CMark spec says about this, but why does Markor say that the file isn't in the same directory?

Markor v1.8.1 from F-Droid

**Comment by gsantner** [comment]
add example of image filename, and the markdown that worked and with not.

**Comment by contrapunctus-1** [comment]
Example file name -
`Soy Milk-Andrea Nguyen-_MG_5338.jpg`

Broken link created by hand -
`![](Soy Milk-Andrea Nguyen-_MG_5338.jpg)`

Broken link created by Markor if file not copied -
`![Soy Milk-Andrea Nguyen-_MG_5338](/storage/4488-1A04/Documents/Text%20Files/cooking/chefsteps.com/Soy%20Milk-Andrea%20Nguyen-_MG_5338.jpg)`

Working link, fixed by hand -
`![](Soy%20Milk-Andrea%20Nguyen-_MG_5338.jpg)`

**Comment by gsantner** [comment]
1) Thats not a correct link, in markdown (i.e. commonmark spec) links need to be URI compliant. Space is illegal in URL, should be `%20`. If your client emacs supports it otherwise, thats nice, but don't expect other applications to work with space itself.
2) That looks alright to me. Created a pic with given filename somewhere in non-notebook folder, selected not copy. The image displays correctly.
3) Just as in *2*, the filename is correct encoded. If you would select *copy OK* you would get the same url/filepath.


![grafik](https://user-images.githubusercontent.com/6735650/60393813-d0688600-9b0a-11e9-80b8-d42339fbccd2.png)

**Comment by contrapunctus-1** [comment]
@gsantner I understand #1, but in case of #2 - the image _was_ in the same folder. Markor wrongly said that it's not.

**Comment by gsantner** [comment]
Ok. Please try to reproduce 2 with v1.8.3 (see github releases for apk). I could not reproduce it myself, so unsure if still happening.
